---
- name: Playbook for Bob
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars:
    my_user:
    my_password:

  tasks:
    - name: Create a new user called Bob
      user:
       name: "{{ my_user }}"
       password: "{{ my_password | password_hash('sha512', 'A512') }}"
       shell: "/bin/{{ my_user }}"
       state: present
       remove: true
       home: /home/bob

    - name: Check if there's a key
      stat: path=/var/lib/jenkins/workspace/Main/public_key.pub
      register: key_exist

    - name: Move Key to bob's user
      command: mv /var/lib/jenkins/workspace/Main/public_key.pub /home/bob/.ssh/
      when: key_exist.stat.exist

    - name: Move readme_bob to bob's directory
      command: mv /var/lib/jenkins/workspace/Main/readme_bob.txt /home/bob/ && chown bob /home/bob/readme_bob.txt && chmod 600 /home/bob/readme_bob.txt
      when: key_exist.stat.exist

    - name: Move readme_bob to bob's directory and set permissions
      command: mv /var/lib/jenkins/workspace/Main/readme_bob.txt /home/bob/
      when: key_exist.stat.exist
...
