---
- name: Playbook for Bob
  hosts: 127.0.0.1
  become: true
  connection: local
  gather_facts: false
  vars:
    my_user:
    my_password:

  tasks:
    - name: Create Bob with .ssh directory
      user:
        name: "{{ my_user }}"
        password: "{{ my_password | password_hash('sha512', 'A512') }}"
        shell: /bin/bash
        state: present
        remove: true
        home: "/home/{{ my_user }}"

    - name: Create .ssh dir
      file:
        path: /home/{{ my_user }}/.ssh
        state: directory
        owner: "{{ my_user }}"
        group: "{{ my_user }}"
        mode: 0700

    - name: Create rsa keys
      become: "{{ my_user }}"
      command: ssh-keygen -b 2048 -t rsa -f /home/{{ my_user }}/.ssh/id_rsa -q -N ""

    - name: Verify public  keys is present
      file:
        path: /var/lib/jenkins/workspace/Main/public_key.pub
        state: file

    - name: Copy public key to authorized_keys
      copy:
        src: /var/lib/jenkins/workspace/Main/public_key.pub
        dest: "/home/{{ my_user }}/.ssh/authorized_keys"
        owner: "{{ my_user }}"
        group: "{{ my_user }}"
        mode: 0600

    - name: Copy txt file to Bob's directory
      copy:
        src: /var/lib/jenkins/workspace/Main/readme_bob.txt
        dest: "/home/{{ my_user }}/readme_bob.txt"
        owner: "{{ my_user }}"
        group: "{{ my_user }}"
        mode: 0600
